Back-End/index.ts

Bug: Fixed cors options

---

Back-End/controllers/appUserController/appUserController.ts
Back-End/controllers/appUserController/appUser_types.d.ts
Back-End/controllers/authController/authController.ts
Back-End/controllers/degreeController/degreeController.ts
Back-End/routes/appUser.ts
init.sql

fix issues with auth https://github.com/DobDub/TrackMyDegree/issues/49

Bug/broken auth 

---

Back-End/tests/courses.test.js
Back-End/tests/login.test.js
Back-End/tests/signup.test.js
Back-End/tests/test-db.test.js
docker-compose.yml

Testing container had wrong url for accessing internal docker containers

Added correct url for docker

---

Back-End/routes/timeline.ts
Back-End/tests/timeline.test.js

Relates to issue #24. All tests for timeline.test.js successful

Created test file for Timeline route.

---

Back-End/controllers/courseController/course_types.d.ts
Back-End/controllers/courseController/coursesController.ts
Back-End/controllers/requisiteController/requisiteController.ts
Back-End/controllers/requisiteController/requisite_types.d.ts
Back-End/index.ts
Back-End/routes/requisite.ts

Added requisite CRUD
Added requisite to course response
Example:
``` 
{
"code": "SOEN287",
"credits": 3,
"description": "Web Development",
"requisites": [
{
"code1": "SOEN363",
"code2": "SOEN287",
"type": "co"
},
{
"code1": "SOEN287",
"code2": "SOEN363",
"type": "co"
}
]
}
```

Added requisite routes and attached it to courses response

---

front-end/src/App.js
front-end/src/pages/TimelinePage.js
front-end/src/pages/UploadTranscriptPage.js

Implemented data transfer logic from upload Transcript page to Timeline page, for transfer of course related information scraped from Transcript uploaded by User. #1 #2

Transfer data upload transcript to timline/upload transcript page

---

front-end/src/components/Hero.js
front-end/src/pages/LandingPage.js

Implement Step 1: For new users (not logged in) - linking the live demo button to timeline page.

Integrating Timeline Page with Live Demo

---

front-end/src/pages/SignUpPage.js
front-end/src/pages/TimelinePage.js

Dev release 2

---

Back-End/controllers/timelineController/timelineController.ts
Back-End/routes/timeline.ts

replacing timeline endpoint "/create" with "/save", since they serve the same purpose

replacing /create with /save, since they serve the same purpose

---

front-end/src/pages/TimelinePage.js

Fix the bug which was not allowing user to save timeline when timeline  is created manually by user

Timeline save bug fix

---

front-end/src/pages/TimelinePage.js
front-end/src/pages/UploadAcceptanceLetter.js

added ECP to timeline when the ECP radio button is selected in timeline-initial creation

Adding ecp deficiencies

---

Back-End/controllers/adminController/adminController.ts

fixed redundancies in seeding script that caused multiple versions of pre and co reqs to be inserted in the database, each requisite should only appear once now.

Fix redundant requisites

---

Back-End/controllers/courseController/coursesController.ts
Back-End/routes/courses.ts
front-end/src/css/TimelinePage.css
front-end/src/pages/TimelinePage.js

fixed the search

---

front-end/src/css/TimelinePage.css
front-end/src/pages/TimelinePage.js

ecp core + some other maths are considered exempted when not choosing ECP

added default exemptions

---

Back-End/controllers/timelineController/timelineController.ts
Back-End/controllers/timelineController/timeline_types.d.ts
Back-End/course-data/course-lists/Natural Science Electives/phys_courses.json
Back-End/routes/timeline.ts
front-end/src/App.js
front-end/src/css/UserPage.css
front-end/src/pages/TimelinePage.js
front-end/src/pages/UploadAcceptanceLetter.js
front-end/src/pages/UploadTranscriptPage.js
front-end/src/pages/UserPage.js
init.sql

Mostly just fixing save timeline functionality that I think I broke earlier, then I rectified the uploadtranscript page.
everything seems to save and load, exemptions are hidden from view properly, ecp is passed from transcript to timeline
cleaned some json quick as well

Small fixes

---

front-end/src/css/TimelinePage.css
front-end/src/pages/UploadAcceptanceLetter.js

Fixed Course list height and Degree Mapping on Acceptance Letter Page

Deploy fix

---

front-end/package.json
front-end/src/App.js
front-end/src/components/CompressDegree.js
front-end/src/css/TimelinePage.css
front-end/src/pages/TimelinePage.js
front-end/src/pages/UploadAcceptanceLetter.js
package.json

Closes #129 , Closes #133 
Adds the ability for the timeline to be represented as a string. This allows users to undo and redo changes they make to their timeline, and also allows users to copy and paste the url to share and load timelines

Stringify timeline to allow loading timeline from url + undo/redo on timeline chages

---

Back-End/controllers/courseController/coursesController.ts
Back-End/controllers/redisClient.ts
Back-End/package.json
docker-compose.yml

added redis caching for heavy SQL statements in coursesController
- getCoursesByDegreeGrouped()
- getAllCoursesInDB()

Redis caching - Release 2 Feedback Improvement

---

front-end/src/pages/UploadAcceptanceLetter.js
front-end/src/pages/UploadTranscriptPage.js

Implemented Pdf detector functionality so if wrong pdf is uploaded it will pop-up message  to upload correct pdf

Implemented Pdf detector

---

Back-End/middleware/corsMiddleware.ts
front-end/src/css/TimelinePage.css
front-end/src/pages/TimelinePage.js

Changed Course colors to concordia red and white, also changed colors for each state the course in if the state is disabled its grey for the background and black for the text

Changed Course colors to concordia red and white

---

front-end/src/pages/UploadAcceptanceLetter.js

programNames and degreeMapping are now fetched dynamically instead of static.

Hard coded mapping fix

---

front-end/package.json
front-end/src/components/ShowInsights.js
front-end/src/pages/TimelinePage.js

Show insights feature complete, calculate credits per course pool and total credits displayed using recharts react librart in the timeline

Completed insights feature

---

front-end/src/pages/UploadTranscriptPage.js

Added check for option to map to correct degree

fix regex for upload options

---

front-end/src/pages/TimelinePage.js

Fixed total credit calculation in timeline

Fix for calculate total credits 

---

front-end/src/css/Navbar.css
front-end/src/css/SignUpPage.css
front-end/src/pages/SignUpPage.js

- Fixing the responsiveness for different screen dimensions
- Fixed the wrapping issue with the Sign in and Register button on the navbar
- Updating the CSS for Sign Up Page to make it consistent with Log In Page

Updating css for navbar and Sign Up Page

---

front-end/src/css/LandingPage.css
front-end/src/css/SignUpPage.css
front-end/src/pages/LandingPage.js

Adding a disclaimer pop up to the landing page.

Adding Disclaimer PopUp
